import Link from 'next/link';
import { ArrowRight, Zap, Users, Mail, Shield, BarChart3, Cpu } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';

export default function Home() {
  const features = [
    {
      icon: Zap,
      title: 'Lead Scraping via Agents',
      description: 'Autonomous AI agents search and identify your ideal prospects across the web using advanced criteria matching.',
    },
    {
      icon: Mail,
      title: 'LLM-Crafted Cold Emails',
      description: 'Personalized emails generated by advanced language models, tailored to each prospect\'s profile and company.',
    },
    {
      icon: Shield,
      title: 'Onchain Lead Tracking',
      description: 'Secure, transparent campaign data stored on Solana blockchain for permanent verification and audit trails.',
    },
  ];

  const benefits = [
    {
      icon: BarChart3,
      title: 'Scale Your Outreach',
      description: 'Process thousands of leads automatically while maintaining personalization at scale.',
    },
    {
      icon: Cpu,
      title: 'AI-Powered Intelligence',
      description: 'Leverage cutting-edge AI to identify high-quality prospects and craft compelling messages.',
    },
    {
      icon: Users,
      title: 'Decentralized Workforce',
      description: 'Tap into a network of specialized AI agents working collaboratively to grow your business.',
    },
  ];

  return (
    <div className="space-y-16">
      {/* Hero Section */}
      <section className="text-center space-y-8">
        <div className="space-y-4">
          <h1 className="text-4xl lg:text-6xl font-bold bg-gradient-to-r from-purple-600 to-blue-600 bg-clip-text text-transparent">
            AI-Powered Lead Generation on Web3
          </h1>
          <p className="text-xl text-gray-600 max-w-3xl mx-auto">
            Run decentralized agents that find, enrich, and write to your ideal customers using JuliaOS and Solana.
          </p>
        </div>
        
        <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
          <Link href="/dashboard">
            <Button size="lg" className="bg-gradient-to-r from-purple-600 to-blue-600 hover:from-purple-700 hover:to-blue-700 px-8 py-4 text-lg">
              Get Started
              <ArrowRight className="ml-2 h-5 w-5" />
            </Button>
          </Link>
          <Button variant="outline" size="lg" className="px-8 py-4 text-lg">
            Watch Demo
          </Button>
        </div>

        {/* Hero Visual */}
        <div className="relative mt-12">
          <div className="mx-auto max-w-4xl">
            <div className="relative rounded-xl bg-gradient-to-r from-purple-100 to-blue-100 p-8 shadow-2xl">
              <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                <div className="bg-white rounded-lg p-6 shadow-lg">
                  <Zap className="h-8 w-8 text-purple-600 mb-3" />
                  <h3 className="font-semibold text-gray-900">AI Agents</h3>
                  <p className="text-sm text-gray-600 mt-2">Autonomous lead discovery</p>
                </div>
                <div className="bg-white rounded-lg p-6 shadow-lg">
                  <Users className="h-8 w-8 text-blue-600 mb-3" />
                  <h3 className="font-semibold text-gray-900">Data Enrichment</h3>
                  <p className="text-sm text-gray-600 mt-2">Enhanced prospect profiles</p>
                </div>
                <div className="bg-white rounded-lg p-6 shadow-lg">
                  <Mail className="h-8 w-8 text-green-600 mb-3" />
                  <h3 className="font-semibold text-gray-900">Smart Outreach</h3>
                  <p className="text-sm text-gray-600 mt-2">Personalized email generation</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="space-y-12">
        <div className="text-center space-y-4">
          <h2 className="text-3xl lg:text-4xl font-bold text-gray-900">
            Core Features
          </h2>
          <p className="text-lg text-gray-600 max-w-2xl mx-auto">
            Everything you need to automate and scale your lead generation process
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {features.map((feature, index) => (
            <Card key={index} className="border-0 shadow-lg hover:shadow-xl transition-shadow duration-300">
              <CardHeader>
                <div className="w-12 h-12 bg-gradient-to-r from-purple-100 to-blue-100 rounded-lg flex items-center justify-center mb-4">
                  <feature.icon className="h-6 w-6 text-purple-600" />
                </div>
                <CardTitle className="text-xl">{feature.title}</CardTitle>
              </CardHeader>
              <CardContent>
                <CardDescription className="text-base leading-relaxed">
                  {feature.description}
                </CardDescription>
              </CardContent>
            </Card>
          ))}
        </div>
      </section>

      {/* Benefits Section */}
      <section className="bg-gradient-to-r from-purple-50 to-blue-50 rounded-2xl p-8 lg:p-12">
        <div className="space-y-12">
          <div className="text-center space-y-4">
            <h2 className="text-3xl lg:text-4xl font-bold text-gray-900">
              Why Choose LeadGenius?
            </h2>
            <p className="text-lg text-gray-600 max-w-2xl mx-auto">
              Transform your lead generation with the power of decentralized AI
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {benefits.map((benefit, index) => (
              <div key={index} className="text-center space-y-4">
                <div className="w-16 h-16 bg-white rounded-full flex items-center justify-center mx-auto shadow-lg">
                  <benefit.icon className="h-8 w-8 text-purple-600" />
                </div>
                <h3 className="text-xl font-semibold text-gray-900">{benefit.title}</h3>
                <p className="text-gray-600 leading-relaxed">{benefit.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="text-center space-y-8">
        <div className="space-y-4">
          <h2 className="text-3xl lg:text-4xl font-bold text-gray-900">
            Ready to Scale Your Lead Generation?
          </h2>
          <p className="text-lg text-gray-600 max-w-2xl mx-auto">
            Join the future of sales automation with AI agents and blockchain technology
          </p>
        </div>
        
        <Link href="/dashboard">
          <Button size="lg" className="bg-gradient-to-r from-purple-600 to-blue-600 hover:from-purple-700 hover:to-blue-700 px-12 py-4 text-lg">
            Start Your First Campaign
            <ArrowRight className="ml-2 h-5 w-5" />
          </Button>
        </Link>
      </section>
    </div>
  );
}